language: node_js

node_js:
  - "10"

cache:
  npm: true

install: npm install

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run migrate:ropsten

  - provider: script
    skip_cleanup: true
    script: npm run migrate:rinkeby

  - provider: script
    skip_cleanup: true
    script: npm run migrate:goerli

  - provider: script
    skip_cleanup: true
    script: npm run migrate:mainnet
