language: node_js

node_js:
  - "10"

cache:
  npm: true

install: npm install

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run deploy:ropsten
    on:
      all_branches: true

#  - provider: script
#    skip_cleanup: true
#    script: npm run deploy:mainnet
#    on:
#      tags: true

  - provider: npm
    skip_cleanup: true
    email: "moody.salem@gmail.com"
    api_key: $TRAVIS_NPM_API_KEY
    on:
      tags: true