language: node_js

node_js:
  - "10"

cache:
  npm: true

install: npm install

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run migrate:ropsten

  - provider: script
    skip_cleanup: true
    script: npm run migrate:mainnet
    on:
      tags: true

after_deploy:
  - "npm run verify"